---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bggdb
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    app: bggdb
  ports:
  - port: 3306
    targetPort: 3306